import puppeteer from "puppeteer";
const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto("http://localhost:5173/", { waitUntil: "networkidle0" });
await page.waitForSelector("aside button");
await page.evaluate(() => document.querySelectorAll("aside button")[4].click());
await page.waitForSelector(".recharts-wrapper");
await new Promise(r => setTimeout(r, 2500));
const charts = await page.$$(".recharts-wrapper");
await charts[0].screenshot({ path: "/tmp/p6-labels.png" });
await browser.close();
