import puppeteer from "puppeteer";
const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 1200 });
await page.goto("http://localhost:5173/", { waitUntil: "networkidle0" });
await page.waitForSelector("aside button");
await page.evaluate(() => document.querySelectorAll("aside button")[5].click());
await page.waitForSelector(".recharts-wrapper");
await new Promise(r => setTimeout(r, 3500));
const main = await page.$("main");
await main.screenshot({ path: "/tmp/p7-full.png" });
await browser.close();
